// generated by stringer -type Severenity; DO NOT EDIT

package gnul

import "fmt"

const _Severenity_name = "UNKNOWINFOWARNINGCRITICAL"

var _Severenity_index = [...]uint8{0, 6, 10, 17, 25}

func (i Severenity) String() string {
	if i < 0 || i >= Severenity(len(_Severenity_index)-1) {
		return fmt.Sprintf("Severenity(%d)", i)
	}
	return _Severenity_name[_Severenity_index[i]:_Severenity_index[i+1]]
}
